import { IconType } from 'react-icons';
import {
  FaWrench,
  FaBriefcase,
  FaCode,
  FaReact,
  FaShip,
  FaGithub,
  FaDog,
  FaServer,
  FaDatabase,
  FaStripe,
} from 'react-icons/fa/index.js';
import {
  MdCodeOff,
  MdEmail,
  MdApi,
  MdFileUpload,
  MdPayment,
  MdDesignServices,
  MdAssistant,
  MdPhoneIphone,
  MdForkLeft,
  MdPhone,
  MdInbox,
  MdFileDownload,
  MdBuild,
  MdImportExport,
  MdTextSnippet,
  MdHouse,
  MdShare,
  MdQuiz,
  MdMusicNote,
  MdPoll,
  MdLanguage,
  MdArrowForward,
  MdCloud,
  MdLock,
  MdLogin,
  MdSearch,
} from 'react-icons/md/index.js';

export enum Icon {
  MdBuild = 'MdBuild',
  MdCodeOff = 'MdCodeOff',
  MdEmail = 'MdEmail',
  MdApi = 'MdApi',
  MdFileUpload = 'MdFileUpload',
  MdPayment = 'MdPayment',
  MdDesignServices = 'MdDesignServices',
  MdAssistant = 'MdAssistant',
  MdPhoneIphone = 'MdPhoneIphone',
  MdForkLeft = 'MdForkLeft',
  MdPhone = 'MdPhone',
  MdInbox = 'MdInbox',
  MdFileDownload = 'MdFileDownload',
  MdImportExport = 'MdImportExport',
  MdTextSnippet = 'MdTextSnippet',
  MdHouse = 'MdHouse',
  MdShare = 'MdShare',
  MdQuiz = 'MdQuiz',
  MdMusicNote = 'MdMusicNote',
  MdPoll = 'MdPoll',
  MdLanguage = 'MdLanguage',
  MdArrowForward = 'MdArrowForward',
  MdCloud = 'MdCloud',
  MdLock = 'MdLock',
  MdLogin = 'MdLogin',
  MdSearch = 'MdSearch',
  FaBriefcase = 'FaBriefcase',
  FaWrench = 'FaWrench',
  FaCode = 'FaCode',
  FaReact = 'FaReact',
  FaShip = 'FaShip',
  FaGithub = 'FaGithub',
  FaDog = 'FaDog',
  FaServer = 'FaServer',
  FaDatabase = 'FaDatabase',
  FaStripe = 'FaStripe',
}

export const Icons: Record<Icon, IconType> = {
  MdBuild,
  MdCodeOff,
  MdEmail,
  MdApi,
  MdFileUpload,
  MdPayment,
  MdDesignServices,
  MdAssistant,
  MdPhoneIphone,
  MdForkLeft,
  MdPhone,
  MdInbox,
  MdFileDownload,
  MdImportExport,
  MdTextSnippet,
  MdHouse,
  MdShare,
  MdQuiz,
  MdMusicNote,
  MdPoll,
  MdLanguage,
  MdArrowForward,
  MdCloud,
  MdLock,
  MdLogin,
  MdSearch,
  FaBriefcase,
  FaWrench,
  FaCode,
  FaReact,
  FaShip,
  FaGithub,
  FaDog,
  FaServer,
  FaDatabase,
  FaStripe,
};
