export enum ErrorNames {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
  PROJECT_DOES_NOT_EXIST = 'PROJECT_DOES_NOT_EXIST',
  PROJECT_INVITATION_INVALID = 'PROJECT_INVITATION_INVALID',
  PROJECT_INVITATION_EXPIRED = 'PROJECT_INVITATION_EXPIRED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
